### ISSUE TITLE
Is there are any demo video for your teleoperation application

### ISSUE THREAD

**Issue by zhangyawen818** [frank-Regal/kinova_ar_teleop#1]

**Comment by frank-Regal** [comment]
@zhangyawen818 Yes, please see the videos attached below that were presented at IROS 2022 XR & Robotics Workshop.

[Basic Demo](https://youtu.be/vra3HZpJcC0?si=w7XHQYPBq0dk_s0V)
[IROS 2022 Presentation](https://youtu.be/wGMj3KUyT4M?si=3Csa4dNT8HqvMiOi)
